language: haskell

matrix:
  allow_failures:
    - env: GHCVER=head
    - env: GHCVER=7.10.1

env:
 - GHCVER=head
 - GHCVER=7.10.1
 - GHCVER=7.8.3
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - travis_retry cabal-1.18 install --only-dependencies --force-reinstalls

